### ISSUE TITLE
EP_01_04 Register Endpoint

### ISSUE THREAD

**Issue by deBubz** [codesydney/woc#11]

**Comment by kimchirice** [comment]
@deBubz  Bao, did you want to creat user model now? 

I could think of adding username/name(maybe first and last)/then email as 1st placeholder in the schema for now

**Comment by deBubz** [comment]
Yeap ive documented it in the drive

**Comment by deBubz** [comment]
also ive opt to not include a username as it'll be 1 less thing to worry about, using an email is fine to login

**Comment by kimchirice** [comment]
hi @deBubz, have you push the code to the repo? saw you marked it done 10 days ago (on 15/05/2021), same day of #10

**Comment by deBubz** [comment]
yep the changes are in branch `ep1_backend_auth`, ill be looking in to setting up API documentation next so the frontend can see what is needed/ returned
