### ISSUE TITLE
 EP_03_05 UserEvents component

### ISSUE THREAD

**Issue by deBubz** [codesydney/woc#45]
Component for the UserDashboard presenting a list of events the user is enrolled in

**Comment by pgayoso** [comment]
The idea is to create a slider of events, with some information of them.
The slider has to have the events order by closer date.

**Comment by pgayoso** [comment]
I have some problems editing the styles of a component.

![image](https://user-images.githubusercontent.com/81002561/120945030-d184a200-c77a-11eb-8184-a987a32f0fad.png)
