### ISSUE TITLE
EP_01_01 Login (front end)

### ISSUE THREAD

**Issue by deBubz** [codesydney/woc#8]
Refer to figma design

**Comment by pgayoso** [comment]
Hi guys, I've just finished with a kind of integration with JSON server to try a login flow.

**Comment by pgayoso** [comment]
https://user-images.githubusercontent.com/81002561/116362469-68d60b80-a845-11eb-8436-54548d4d663c.mov

**Comment by kimchirice** [comment]
thought we good to close this issue. @pgayoso @deBubz

**Comment by deBubz** [comment]
I kinda butchered it trying to apply `useForm` ill fix it up a bit then close it
