### ISSUE TITLE
Review Current Production build build

### ISSUE THREAD

**Issue by deBubz** [codesydney/woc#87]
Problem:
Current Deployed site is returning this error
![image](https://user-images.githubusercontent.com/22888127/144059088-254a49a8-c90d-4856-818e-481a38aa4bb4.png)

Task:
Check Heroku logs and fix the deployment build

**Comment by deBubz** [comment]
OK theres still 1 missing dot env import in events controller

> just remember to change this in the next branch merge

**Comment by engramar** [comment]
Thanks @deBubz  for looking into this. Please let me know of the link to the WIP so we can share it with Brenda next week. Cheers.
